version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  acacia:
    container_name: acacia-landing
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8080:80"
    labels:
      - traefik.backend=acacia
      - traefik.frontend.rule=Host:acacia.eco,www.acacia.eco
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
